theme: jekyll-theme-minimal
collections:
    exercises:
        output: true
        permalink: :collection/:name:output_ext
    quizzes:
        output: true
        permalink: :collection/:name:output_ext
videourl: "http://people.duke.edu/~jmp33/matlab-neurobio/videos"
